version: '3.8'

services:
  db:
    container_name: anime-db
    image: postgres
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    container_name: anime-dojo-frontend
    build: ./anime_dojo
    image: "josephse91/anime-dojo-frontend"
    ports: 
      - "5000:5000"
  user-api:
    container_name: user-api
    build: ./user_api
    image: "josephse91/anime_user_api"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  show-ratings-api:
    container_name: show-ratings-api
    build: ./show_ratings_api
    image: "josephse91/show_ratings_api"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3001"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3001:3001"
    depends_on:
      - db
    tty: true
    stdin_open: true
  likes-api:
    container_name: likes-api
    build: ./likes_api
    image: "josephse91/likes_api"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3002"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3002:3002"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  postgres:

networks:
  default:
    name: "anime-dojo-network"